### ISSUE TITLE
Rule a08_sdgeAR_segment – ficture/script/make_sge_by_hexagon.py doesn't exist

### ISSUE THREAD

**Issue by elubeck** [seqscope/NovaScope#8]
Hi,

This rule can't find this script (make_sge_by_hexagon.py).  I'm pointing to a pip installed version of ficture, but I also don't see it in the ficture github repo.

Thanks!

**Comment by WQ-CHENG** [comment]
Hello Lubeck,

Thank you for your feedback. Currently, NovaScope uses the stable branch of FICTURE, which should be the source of this error. Could you please switch FICTURE to its stable branch by following the commands listed below? Additionally, ensure you specify the FICTURE path in the config_env.yaml file. Please let me know if the issue persists. 

We are actively working to update our pipeline and appreciate your input, which will be incorporated into the new version to enhance usability. However, because these updates are not yet finalized, it is essential to use the stable branch for now.

Here are the commands to switch the branch of FICTURE:
```
## Please replace the /path/to/ficture/repo with the location of your FICTURE directory
ficture_dir=/path/to/ficture/repo                
cd $ficture_dir

## This command lists all branches, including local and remote ones
git branch -a 

## Switch to the stable branch
git checkout stable

## Double-check your current branch. The branch marked with an asterisk is the active one.
git branch    

## Locate the make_sge_by_hexagon.py script
ls -hlt script/make_sge_by_hexagon.py  
```

Best,
Weiqiu

**Comment by elubeck** [comment]
Thanks!
